#!/bin/sh

docker login $DOCKER_REGISTRY -u $DOCKER_USER -p$DOCKER_PASSWD &&
docker pull $DOCKER_REPOSITORY:$CIRCLE_SHA1 ||
docker build -t $DOCKER_REPOSITORY:$CIRCLE_SHA1 . &&
docker push $DOCKER_REPOSITORY:$CIRCLE_SHA1

if ! test -z $CIRCLE_TAG; then
  docker tag $DOCKER_REPOSITORY:$CIRCLE_SHA1 $DOCKER_REPOSITORY:$CIRCLE_TAG
  docker push $DOCKER_REPOSITORY:$CIRCLE_TAG
fi